config/routes.rb
LunchLottery::Application.routes.draw do

  root :to => "people#welcome"

  resources :locations, :only => [:new, :create] do
    resources :restaurants, :only => [:new, :create]
  end

  get "people/:token" => "people#update", :as => :person_token
  get ":location" => "people#index", :as => :location
  post "people" => "people#create"

  match ':controller(/:action(/:id(.:format)))' # TODO:KILL ME

end

app/models/dates.rb
class Dates
  def self.isday?(date, weekday)
    date.strftime("%A").casecmp(weekday) == 0
  end

  def self.next_occurrence (weekday)
    now = DateTime.now.to_date
    now = now.next until isday?(now, weekday)
    now.to_datetime + 1.day - 1.second
  end

  def self.day_before(day_name)
    (Date.parse(day_name) - 1.day).strftime("%A")
  end
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  meeting_point :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  address       :string(255)
#  longitude     :float
#  latitude      :float
#  weekday       :string(255)
#

 class Location < ActiveRecord::Base
  has_many :people
  has_many :location_restaurants
  has_many :restaurants, :through => :location_restaurants
  validates_presence_of :address

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def to_param
    name
  end
end

app/models/location_restaurant.rb
# == Schema Information
#
# Table name: location_restaurants
#
#  id            :integer         not null, primary key
#  location_id   :integer
#  restaurant_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class LocationRestaurant < ActiveRecord::Base
  belongs_to :location
  belongs_to :restaurant

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id                   :integer         not null, primary key
#  email                :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  authentication_token :string(255)
#  location_id          :integer
#  subscribed           :boolean         default(TRUE)
#  opt_in_datetime      :datetime
#

class Person < ActiveRecord::Base
  validates :email, :email => true
  validates_uniqueness_of :email
  validates_presence_of :location

  before_create :generate_authentication_token

  belongs_to :location
  
  scope :opted_in, where("opt_in_datetime IS NOT null and opt_in_datetime >= ?", DateTime.now)
  scope :subscribed, where(:subscribed => true)

  def self.find_by_authentication_token!(token)
    find_by_authentication_token(token) or raise "I couldn't find that token."
  end

  def going?
    Person.opted_in.where(:id => self).exists?
  end

  def gravatar_url
    email_address = self.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "http://www.gravatar.com/avatar/#{hash}?s=50"
  end

  protected

  def generate_authentication_token
    loop do
      self.authentication_token = ActiveSupport::SecureRandom.base64(15).tr('+/=', 'xyz')
      break unless self.class.find_by_authentication_token(self.authentication_token)
    end
  end
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  address    :string(255)
#  longitude  :float
#  latitude   :float
#  created_at :datetime
#  updated_at :datetime
#

class Restaurant < ActiveRecord::Base
  validates_presence_of :name, :address

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  rescue_from RuntimeError, :with => :oh_noes

  protected

  def oh_noes(exception)
    flash[:error] = exception.message
    render "application/error", :status => 400
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def create
    @location = Location.new(params[:location])
    @location.save!

    redirect_to root_path
  rescue
    render :action => :new
  end

  def new
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :load_location, :only => [:index, :create]

  def index
    @person = Person.new
    load_people()
  end

  def welcome
  end

  def create
    @person = Person.new(params[:person].merge(:location => @location))
    if @person.save
      flash[:message] = "Cool, you're signed up!"
      redirect_to location_path(@location)
    else
      load_people()
      render :template => "people/index"
    end
  end

  def update
    @person = Person.find_by_authentication_token!(params[:token])
    
    if @person.update_attributes(params[:person])
      flash[:notice] = "Your settings have been updated."
    else
      flash[:error] = "I had a problem saving that."
    end

    @changed_opt_in_datetime = params[:person].has_key?(:opt_in_datetime)
    @changed_subscription = params[:person].has_key?(:subscribed)
    @people = Person.opted_in.where(:location_id => @person.location_id)
    
    render :edit
  end
  
  private

  def load_location
    @location = Location.find_by_name(params[:location])
    if @location.nil?
      redirect_to root_path
      return
    end
  end

  def load_people
    people = @location.people
    @opted_in_people = people.opted_in
    @non_opted_in_people = people - @opted_in_people
    @people_count = people.count
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def new
    @location = Location.find_by_name(params[:location_id])
  end

  def create
    @location = Location.find_by_name(params[:location_id])
    @location.restaurants.create!(params[:restaurant])
    redirect_to location_path(@location)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
  def google_map_marker(color, label, lat, lng)
    "markers=color:#{color}%7Clabel:#{label}%7C#{lat}%2C#{lng}"
  end

  def google_map_url(location)
    url = "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false"

    url += "&" + google_map_marker("green", "", location.latitude, location.longitude)
    location.restaurants.each_with_index do |restaurant, index|
      url += "&" + google_map_marker("red", google_map_pin_label(index), restaurant.latitude, restaurant.longitude)
    end

    url
  end

  def google_map_pin_label(index)
    ('A'.ord + (index % 26)).chr
  end
end

app/views/application/error.html.haml
%h2 Oops!

%p= flash[:error]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Lunch Lottery
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    = link_to(image_tag("lottery.jpg", :size => "84x80"), "/")

    = yield

app/views/locations/new.html.haml
%h3 Create A New Location

= form_for @location || Location.new do |f|
  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.label :meeting_point
    = f.text_field :meeting_point
  %div
    = f.label :address
    = f.text_field :address
  %div
    = f.submit

app/views/notifier/invite.html.haml
%p Hello from lunchlottery.com!

%p
  = @opted_in_count 
  people of
  = @total_people.size
  were available for lunch this week and were divided into
  - @group_stats.keys.each_with_index do |group_size, index|
    = pluralize(@group_stats[group_size], "group")
    of
    = group_size
    people
    = ' and ' unless index == @group_stats.size - 1

%p You are all going to lunch together tomorrow:

%ul
  - @people.each do |person|
    %li
      %img{ :src => person.gravatar_url }
      = person.email

%p= @location.meeting_point

app/views/notifier/remind.html.haml
%p Hello from lunchlottery.com!

%p Want to lunch with some random people on #{@person.location.weekday}?

%ul
  %li
    <b>Yes!</b>
    = link_to "I would like to go to lunch this week!", person_token_url(@person.authentication_token, :person => {:opt_in_datetime => Dates.next_occurrence(@person.location.weekday)})

  %li
    <b>No, thanks.</b>
    I'm busy this week.

  %li
    <b>No, thanks.</b>
    = link_to "I would like to stop receiving these emails.", person_token_url(@person.authentication_token, :person => {:subscribed => false})

app/views/people/edit.html.haml
= form_for @person, :url => person_token_path(@person.authentication_token), :html => {:method => :get} do |f|
  - if @changed_opt_in_datetime
    %p
      <b>#{@person.email}</b> is #{@person.going? ? "going" : "not going"} this week.

    %p
      - if @person.going?
        = f.hidden_field :opt_in_datetime, :value => nil
        = f.submit "Actually, I don't want to go"
      - else
        = f.hidden_field :opt_in_datetime, :value => Dates.next_occurrence(@person.location.weekday)
        = f.submit "Actually, I want to go"
  - if @changed_subscription
    %p
      <b>#{@person.email}</b> is #{@person.subscribed ? "subscribed" : "unsubscribed"}.

%h3 People at #{@person.location.name} who've already opted-in
%div#people_at_location
  - @people.each do |person|
    %img{ :src => person.gravatar_url, :class => "gravatar in" }

app/views/people/index.html.haml
%h1 Lunch Lottery @#{@location.name}

%p
  <b>#{Linguistics::EN.numwords(@people_count).titlecase} people</b>
  are going to lunch in random groups of 4 <b>every #{@location.weekday}.</b>

- unless @person.errors.empty?
  %p.errors
    = @person.errors.full_messages

- if flash[:message]
  %p.flash
    = flash[:message]

- if @person.errors.empty? && !flash[:message]
  %p Sign up below! We'll pick your lunch mates and email you on #{Dates.day_before(@location.weekday)} night.

= form_for @person do |f|
  = f.label :email, "Email:"
  = f.text_field :email
  = hidden_field_tag :location, @location.name

  = f.submit "Sign me up!"


%h3 People at #{@location.name}
.opted_in
  %h4 People who are going
  - @opted_in_people.each do |person|
    %img{ :src => person.gravatar_url, :class => "gravatar in" }
.non_opted_in
  %h4 People who are not (yet) going
  - @non_opted_in_people.each do |person|
    %img{ :src => person.gravatar_url, :class => "gravatar out" }
%div
  %small
    If your profile picture doesn't show up here, sign up with
    = succeed "." do
      %a{:href=>"http://en.gravatar.com/site/signup/"} gravatar

%h3 Favorite Restaurants for #{@location.name}

- if @location.restaurants.present?
  %img{:src => google_map_url(@location)}
  %ul
    - @location.restaurants.each_with_index do |restaurant, index|
      %li
        %p
          %img{:src => "http://www.google.com/mapfiles/marker#{google_map_pin_label(index)}.png"}
          = restaurant.name + ": " + restaurant.address

%div
  = link_to "Add A Restaurant for #{@location.name}", new_location_restaurant_path(@location), :alt => "foo"

app/views/people/welcome.html.haml
%h1 Lunch Lottery

%p
  Go to lunch in random groups of 4 <b>every week.</b>

%h3 Pick your location:

- Location.all.each do |location|
  %p
    = link_to(location.name, location_path(location))


%p
  = link_to("Or, start a new lunch lottery", new_location_path, :id => "create_location")

app/views/reminder/reminder.html.haml
%p Hello from lunchlottery.com!

%p You are all going to lunch together tomorrow:

%ul
  - @addresses.each do |address|
    %li= address
    
%p How about 12:30 at the elevators?

app/views/restaurants/new.html.haml
%h3 Create A New Restaurant

= form_for @restaurant || Restaurant.new, :url =>  location_restaurants_path(:location_id => @location.to_param) do |f|
  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.label :address
    = f.text_field :address
  %div
    = f.submit